#!/usr/bin/env bash

#description: Builds all binaries

readonly config="${1}"
function getConfig() {
  if [[ -z "${config}" ]]; then
    echo "-prod"
  else
    echo ""
  fi
}

readonly destinationDir="build/versions"
if [[ ! -d "${destinationDir}" ]]; then
  mkdir -p "${destinationDir}"
fi
readonly versionFile="version.txt"
readonly version="$(git describe --tags --abbrev=0 2>/dev/null | tr -d '\n')"
echo "${version:-"0.1.0"}" > "${destinationDir}/${versionFile}"
find Sources -type d -name "img*" -exec cp "${destinationDir}/${versionFile}" {}/"${versionFile}" \;

readonly targetConfig="$(getConfig)"
while read -r toolName; do
  make "${toolName}${targetConfig}"
done < <(grep 'executable' Package.swift | grep targets  | cut -d'"' -f2)
