#!/usr/bin/env bash

#description: Delete build artifacts

readonly versionFile="version.txt"

readonly config="${1}"
if [[ -n "${config}" ]]; then
  echo "skip" > /dev/stderr
  exit 0
fi

swift package clean
rm -rf build
find . -type f -name "${versionFile}" \
  -print \
  -exec rm {} \;
