name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: "tag name for this release"
        required: true
        type: string

jobs:
  release:
    name: Release x86_64
    runs-on: macos-13
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v1
        name: Configure Swift version
        with:
          swift-version: "5.9.0"

      - name: Show Swift version
        run: swift --version

      - name: Build artifact
        run: make build

      - name: Pick binaries
        run: make pick

      - name: Create release
        run: make create-release
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_VERSION: ${{ inputs.version }}

      - name: Upload artifact
        run: make upload
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_VERSION: ${{ inputs.version }}
