name: run swift test

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show Swift version
        run: swift --version

      - name: Run Tests
        run: make test

      - name: Build artifact
        run: make build

      - name: Show dependencies
        run: make run-otool

      - name: Upload snapshot artifact
        uses: actions/upload-artifact@v1
        with:
          name: imgcopy
          path: .build/x86_64-apple-macosx/release/imgcopy
