name: run swift test

on:
  push:
    branches:
      - main
      - master
      - feature/*

jobs:
  test:
    strategy:
      matrix:
        runner:
          - macos-13
#          - macos-13-xlarge
    runs-on: ${{ matrix.runner }}
    name: "Test on ${{ matrix.runner }}"
    steps:
      - name: Show CPU Name
        run: sysctl -n "machdep.cpu.brand_string"

      - name: Checkout
        uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v1
        name: Configure Swift version
        with:
          swift-version: "5.9.0"

      - name: Show Swift version
        run: swift --version

      - name: Run Tests
        run: make test

      - name: Build artifact
        run: make build

      - name: Show path
        run: make show-path

      - name: Pick binaries
        run: make pick

      - name: Show binaries
        run: find build -type f -exec test -x {} \; -print

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "test-report-${{ matrix.runner }}"
          path: build/test
